/* Analyze */
options nodate nonumber;
%let outpath=/home/u49946413/ECRB94/output;
ods rtf file="&outpath/Tourism_case_study.rtf";

ods noproctitle;

*The number of arrivals, Departures in 2014 for each continent;

title "Stats of Avrrival and Departure Tourists by Continents in 2014";
title2 "Summary of Arrivals";
proc means data=cr.final_tourism mean min max maxdec=0 nonobs;
	where Category in ("Arrivals");
	class Continent;
	var Y2014;
run;
title2 "Summary of Departures";
proc means data=cr.final_tourism mean min max maxdec=0 nonobs;
	where Category in ("Departures");
	class Continent;
	var Y2014;
run;
title;

* Europe is the most popular continet people like to travel, the second popular continent is then Aisa.
* In addition, people from Europe are also more likely to travle the world, while North Americans are the second place to travel.;


* Which Coutry in Europe and Asia can attract most tourists?;
title "European Countries with most Tourists";
proc sql;
	select Country_Name, mean(Y2014) as Avg_Tourists
	from cr.final_tourism
	where Tourism_Type="Inbound tourism" and Continent=3 and Category="Arrivals"
	group by Country_Name
	order by Avg_Tourists Desc;
quit;
title;

* France and Spain;
	
title "Asian Countries with most Tourists";
proc sql;
	select Country_Name, mean(Y2014) as Avg_Tourists
	from cr.final_tourism
	where Continent=5 and Category="Arrivals"
	group by Country_Name
	order by Avg_Tourists Desc;
quit;
title;
	
* China and Russia Federation;
	
	
* Which Coutry in Europe and North America are more likely to travel;
title "European Countries with most travelers";
proc sql;
	select Country_Name, mean(Y2014) as Avg_Tourists
	from cr.final_tourism
	where Continent=3 and Category="Departures"
	group by Country_Name
	order by Avg_Tourists Desc;
quit;
title;

* Germany and UK;
	
title "North American Countries with most travelers";
proc sql;
	select Country_Name, mean(Y2014) as Avg_Tourists
	from cr.final_tourism
	where Tourism_Type="Outbound tourism" and Continent=1 and Category="Departures"
	group by Country_Name
	order by Avg_Tourists Desc;
quit;
title;
* USA and Canada

* Which continent would generate most income by worldwide travelers;
title "Average of Generated Tourists Income by Continent";
proc means data=cr.final_tourism mean nonobs;
	where Category="Tourism expenditure in the country - US$";
	var Y2014;
	class Continent;
run;
title;

* North America and Europe

* Which continent would spend most expenses on traveling;
title "Average of Tourists Spending by Continent";
proc means data=cr.final_tourism mean nonobs;
	where Category="Tourism expenditure in other countries - US$";
	var Y2014;
	class Continent;
run;
title;

* Europe and North America


* Which Country in North America and Europe generate most income by worldwide travelers;
title "North America Countries with most Income by Tourists";
proc sql;
	select Country_Name, sum(Y2014) as Sum_Income
	from cr.final_tourism
	where Continent=1 and Category="Tourism expenditure in the country - US$"
	group by Country_Name
	order by Sum_Income Desc;
quit;
title;

title "European Countries with most Income by Tourists";
proc sql;
	select Country_Name, sum(Y2014) as Sum_Income
	from cr.final_tourism
	where Continent=3 and Category="Tourism expenditure in the country - US$"
	group by Country_Name
	order by Sum_Income Desc;
quit;
title;


* Seperate into two tables based on bound direction;
data inbound outbound;
	set cr.final_tourism(drop=Series);
	if Tourism_Type="Inbound tourism" then output inbound;
		else output outbound;
	drop Tourism_Type;
run;

* Sum Expenditures for each country based on bound direction;
data inbound_expenditure;
	set work.inbound;
	format Inbound_Sum dollar24.;
	where Category~="Arrivals";
	
	if first.Country_Name=1 then Inbound_Sum=0;
	Inbound_Sum+Y2014;
	
	if last.Country_Name=1;
	by Country_Name;
	drop Category Y2014;
run;
	
data outbound_expenditure;
	set work.outbound;
	format Outbound_Sum dollar24.;
	where Category~="Departures";
	
	if first.Country_Name=1 then Outbound_Sum=0;
	Outbound_Sum+Y2014;
	
	if last.Country_Name=1;
	by Country_Name;
	drop Category Y2014;
run;

* Combine two expenditures tables created above;
data cr.expenditure;
	merge inbound_expenditure outbound_expenditure(drop=Continent);
	by Country_Name;
run;

* Create final_expenditure table by removing coutries with $0 sum;
data cr.final_expenditure;
	set cr.expenditure;
	where Inbound_Sum~=0 or Outbound_Sum~=0;
	format Income dollar24.;
	Income=Inbound_Sum-Outbound_Sum;
	by Country_Name;
run;

* Negative Income means foreigners spend less money than local people spend to other countries;

title "Countries with most Income generated by Tourists";
proc sql;

	select Country_Name, Continent, Income
	from cr.final_expenditure
	where Income>0
	order by Income desc, Continent;
quit;

title;

title "Countries with most Expenditures caused by Travelers";
proc sql;
	select Country_Name, Continent, Income
	from cr.final_expenditure
	where Income<0
	order by Income, Continent;
quit;
title;

ods proctitle;
ods rtf close;